GET https://progwebti2-grupo2-webapp.azurewebsites.net/carrera
########

POST https://progwebti2-grupo2-webapp.azurewebsites.net/carrera
Content-Type: application/json

    { "nombre": "Ingenieria de Sistemas", "idUniversidad": 1}
###

PUT http://localhost:3001/persona/
Content-Type: application/json

{
        "id": 6,
        "nombre": "Leon",
        "apellido":"Salaz",
        "tipoDocumento":"DNI",
        "numeroDocumento":"76569006",
        "idRol": 1,
        "email": "Leo2",
        "password": "broder2",
        "idCarrera": 21,
        "tituloPresentacion": "Esta es mi presentacion como alumno",
        "presentacion": "Buenos dias, mi nombre es Leon Salaz"
      }

###

GET http://localhost:3001/persona/2
###

DELETE http://localhost:3001/cita/2

########
